# Netlify Configuration
[build]
  # Don't run any build command - we'll deploy static files and functions only
  command = ""
  publish = "public"
  functions = "netlify/functions"

# Redirect rules for GDPR webhooks
[[redirects]]
  from = "/webhooks/gdpr/customers_data_request"
  to = "/.netlify/functions/customers_data_request"
  status = 200

[[redirects]]
  from = "/webhooks/gdpr/customers_redact"
  to = "/.netlify/functions/customers_redact"
  status = 200

[[redirects]]
  from = "/webhooks/gdpr/shop_redact"
  to = "/.netlify/functions/shop_redact"
  status = 200
