# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "976cade99d33d671b6148dd28f7cc487"
name = "single-date-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
