# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "976cade99d33d671b6148dd28f7cc487"
name = "single-date-app"
application_url = "https://ebruzzi.github.io/single-date-app"
embedded = true

[webhooks]
api_version = "2026-01"

[auth]
redirect_urls = [ "https://ebruzzi.github.io/single-date-app/auth/callback" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

# Mandatory GDPR compliance webhooks
[webhooks.privacy_compliance]
# These webhooks are required for GDPR compliance
# Since this is a function-only app with no data storage, the endpoints acknowledge but don't process data

[[webhooks.privacy_compliance.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "https://ebruzzi.github.io/single-date-app/webhooks/gdpr/customers_data_request"

[[webhooks.privacy_compliance.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "https://ebruzzi.github.io/single-date-app/webhooks/gdpr/customers_redact"

[[webhooks.privacy_compliance.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "https://ebruzzi.github.io/single-date-app/webhooks/gdpr/shop_redact"
