# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "976cade99d33d671b6148dd28f7cc487"
name = "single-date-app"
application_url = "https://single-date-validator.netlify.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://single-date-validator.netlify.app/auth/callback" ]

[webhooks]
api_version = "2026-01"

[webhooks.privacy_compliance]
customer_deletion_url = "https://single-date-validator.netlify.app/webhooks/gdpr/customers_redact"
customer_data_request_url = "https://single-date-validator.netlify.app/webhooks/gdpr/customers_data_request"
shop_deletion_url = "https://single-date-validator.netlify.app/webhooks/gdpr/shop_redact"
